server:
  port: ${ACCOUNT_PORT}

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
